import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Walmart Product Client",
  description: "Generated by create next app",
};

export default function DefaultLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
      <Image
        className="dark:invert"
        src="https://nextjs.org/icons/next.svg"
        alt="Next.js logo"
        width={180}
        height={38}
        priority
      />

      <main className="w-full h-full">
        {children}
      </main>
    </div>
  );
}
